# Site settings
title: Toolkit for Efficient Analysis
email: jeremi.niedziela@cern.ch
description: >
  Documentation for the tea [Toolkit for Efficient Analysis]
lang: en-US

baseurl: "/tea/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
git_address: https://github.com/jniedzie/tea

# theme options from https://bootswatch.com/3/
bootwatch: simplex ## would be nice to modify red to be like in journal

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  # - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
